## Custom Training for Word2Vec

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import gensim
import nltk

In [2]:
nltk.download("all")

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |  

True

In [3]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [4]:
story = []

In [5]:
for file in os.listdir("/content/drive/MyDrive/GEN AI ineuron/got_data"):
  print(file)

004ssb.txt
002ssb.txt
003ssb.txt
001ssb.txt
005ssb.txt


In [6]:
f = open(r"/content/drive/MyDrive/GEN AI ineuron/got_data/004ssb.txt",encoding = "unicode_escape")
corpus = f.read()
raw_sent = sent_tokenize(corpus)

In [7]:
for i in raw_sent:
  print(simple_preprocess(i))

Streaming output truncated to the last 5000 lines.
['oh', 'aye']
['six', 'and', 'ten', 'for', 'him', 'and', 'three', 'for', 'you', 'that', 'made', 'no', 'sense', 'to', 'cersei']
['her', 'thumb', 'was', 'throbbing', 'where', 'she', 'cut', 'it', 'and', 'her', 'blood', 'was', 'dripping', 'on', 'the', 'carpet']
['how', 'could', 'that', 'be']
['she', 'wanted', 'to', 'ask', 'but', 'she', 'was', 'done', 'with', 'her', 'questions']
['the', 'old', 'woman', 'was', 'not', 'done', 'with', 'her', 'however']
['gold', 'shall', 'be', 'their', 'crowns', 'and', 'gold', 'their', 'shrouds', 'she', 'said']
['and', 'when', 'your', 'tears', 'have', 'drowned', 'you', 'the', 'valonqar', 'shall', 'wrap', 'his', 'hands', 'about', 'your', 'pale', 'white', 'throat', 'and', 'choke', 'the', 'life', 'from', 'you', 'what', 'is', 'valonqar']
['some', 'monster', 'the', 'golden', 'girl', 'did', 'not', 'like', 'that', 'foretelling']
['you', 're', 'liar', 'and', 'warty', 'frog', 'and', 'smelly', 'old', 'savage', 'and', 'do

In [8]:
for filename in os.listdir("/content/drive/MyDrive/GEN AI ineuron/got_data"):
  file_path = os.path.join("/content/drive/MyDrive/GEN AI ineuron/got_data",filename)
  with open(file_path,encoding  = "unicode_escape") as f:
    corpus = f.read()
  raw_sent = sent_tokenize(corpus)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))

In [9]:
len(story)

145020

In [11]:
model  = gensim.models.Word2Vec(window = 5,min_count = 2,vector_size = 4)

In [12]:
model.build_vocab(story)

In [13]:
model.corpus_count

145020

In [14]:
model.epochs

5

In [15]:
model.corpus_total_words

1725638

In [16]:
model.min_count

2

In [18]:
model.train(story, total_examples = model.corpus_count, epochs = model.epochs)

(6569602, 8628190)

In [19]:
len(model.wv["king"])

4

In [21]:
model.wv["man"]

array([-1.7939943, -1.1084151,  1.3673291,  1.1606168], dtype=float32)

In [22]:
model.wv["woman"]

array([-1.3165512, -1.5557755,  1.0180913,  1.6714332], dtype=float32)

In [23]:
model.wv["king"]

array([-5.267709  ,  0.37536824,  3.0811691 , -3.1207807 ], dtype=float32)

In [24]:
model.wv["queen"]

array([-4.3006077 , -0.15009683,  2.45546   ,  0.06528491], dtype=float32)

In [25]:
model.wv.most_similar("king")

[('shush', 0.9980923533439636),
 ('paramount', 0.9970818758010864),
 ('chancy', 0.9966591000556946),
 ('spinal', 0.9952007532119751),
 ('kingslaying', 0.9932164549827576),
 ('forbearance', 0.9888303279876709),
 ('razors', 0.9884421229362488),
 ('advances', 0.9872598648071289),
 ('targaryen', 0.9868462085723877),
 ('tottering', 0.9861644506454468)]

In [26]:
model.wv.most_similar("queen")

[('robert', 0.9988691210746765),
 ('mother', 0.9980777502059937),
 ('father', 0.9967262744903564),
 ('stannis', 0.9963224530220032),
 ('uncle', 0.9958081245422363),
 ('rolls', 0.9952946901321411),
 ('sister', 0.9945196509361267),
 ('husband', 0.9933621883392334),
 ('unfailingly', 0.993257999420166),
 ('grace', 0.9929862022399902)]

In [27]:
model.wv.most_similar("daenerys")

[('fellowship', 0.9991385340690613),
 ('prospects', 0.998928964138031),
 ('torturers', 0.9968156218528748),
 ('priestly', 0.9962772130966187),
 ('ar', 0.9957093000411987),
 ('st', 0.9948673844337463),
 ('marry', 0.9947524070739746),
 ('redoubtable', 0.9940415620803833),
 ('shoves', 0.9922573566436768),
 ('defeats', 0.9919669032096863)]

In [29]:
model.wv.doesnt_match(['jon','robb','arya','sansa','bran'])

'robb'

In [30]:
model.wv.get_normed_vectors()

array([[ 0.19923781, -0.734922  ,  0.03785162, -0.6471177 ],
       [ 0.20947663, -0.8738837 , -0.02007059, -0.43822822],
       [ 0.04907211, -0.19429353,  0.945409  ,  0.25699016],
       ...,
       [-0.9585099 ,  0.10628726, -0.20617007,  0.16569775],
       [-0.04184184, -0.8373697 ,  0.34385604,  0.4228762 ],
       [ 0.12089185, -0.51237565,  0.82271993, -0.21444881]],
      dtype=float32)

In [31]:
model.wv.get_normed_vectors().shape

(17453, 4)

In [32]:
len(model.wv.index_to_key)

17453

In [ ]:
#model.save("word2vec.model")

In [ ]:
#model.save("word2vec.bin")

In [33]:
#!gzip word2vec.bin > word2vec.bin.gz